version: '1.2'
services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
        - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://host.docker.internal:8080

  worker:
    image: locustio/locust
    volumes:
        - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    depends_on:
      - master


# up -d --scale worker=3