spring:
  r2dbc:
    url: r2dbc:mysql://localhost:13306/test?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
logging:
  level:
    org:
      springframework:
        web: DEBUG
        r2dbc: DEBUG
        transaction: DEBUG
psp:
  toss:
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com