spring:
  application:
    name: coupon-consumer
server:
  port: 8081

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    web:
      exposure:
        include: prometheus