spring:
  profiles:
    active: stress
---
spring:
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db-init/schema.sql

logging:
  level:
    kr.jay.webfluxreactor: DEBUG
#    org.springframework.r2dbc.core: DEBUG

---
spring:
  config:
    activate:
      on-profile: stress
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/sample
    username: user
    password: 1234
  sql:
    init:
      mode: never