spring:
  output:
    ansi:
      enabled: always
  application:
    name: payment
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/payment
    username: user
    password: 1234
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
      data-locations: classpath:db-init/test-data.sql
  data:
    redis:
      host: localhost
      port: 6379
  thymeleaf:
    cache: off

logging:
  level:
    kr.jay.kr.jay.payment: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection.init: debug
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: off
    org.springframework.web.HttpLogging: off
  pattern:
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%logger|%blue(\\(%F:%L\\))|%msg%n"

server:
  shutdown: graceful
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always

payment:
  toss:
    domain: https://api.tosspayments.com
    key:
      client: test_ck_ttttttqrterqtewrtwertwertewrtwert
      secret: flajewfiojaewiufhawesiufhiAFEIHIWSEUFHeiauwhfiuawhef2
---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/payment
  sql:
    init:
      mode: always
      data-locations: ""