spring:
  profiles:
    active: stress
---
spring:
  application:
    name: spring-mvc
  output:
    ansi:
      enabled: always

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    kr.jay: debug
---
spring:
  config:
    activate:
      on-profile: stress
  datasource:
    url: jdbc:mariadb://localhost:3306/sample
    username: user
    password: 1234