name: Build and Deploy

on:
  push:
    branches: [ "main" ]

env:
  HOST: host
  USER_NAME: username
  PASSWORD: password
  PORT: port

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: run script
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER_NAME }}
          password: ${{ env.PASSWORD }}
          port: ${{ env.PORT }}
          script: |
            D:\WORKSPACE\deploy.bat

      - name: Send build file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER_NAME }}
          password: ${{ env.PASSWORD }}
          port: ${{ env.PORT }}
          source: ".gitignore"
          target: D:\WORKSPACE